### ISSUE TITLE
Failed to activate the buildium package

### ISSUE THREAD

**Issue by mohdsaadhamid** [atom-community/buildium#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [buildium](https://github.com/idleberg/atom-buildium) package 0.75.5

### Stack Trace

Failed to activate the buildium package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StatusBarView.addLeftTile (<embedded>:11:970383)
    at r.value (/packages/buildium/lib/buildium.js:1:44554)
    at /packages/buildium/lib/buildium.js:1:44308
    at Config.observeKeyPath (<embedded>:11:336878)
    at Config.observe (<embedded>:11:331360)
    at Object.observe (/packages/buildium/lib/buildium.js:1:30334)
    at /packages/buildium/lib/buildium.js:1:44267)
    at Object.consumeStatusBar (/packages/buildium/lib/buildium.js:1:64577)
    at Provider.provide (<embedded>:14:1097820)
    at ServiceHub.consume (<embedded>:11:3479960)
    at Package.activateServices (<embedded>:11:3488291)
    at Package.activateNow (<embedded>:11:3485046)
    at <embedded>:14:2607
    at Function.simpleDispatch (<embedded>:11:1182710)
    at Emitter.emit (<embedded>:11:1184151)
    at <embedded>:11:385312
    at Set.forEach (<anonymous>:null:null)
    at PackageManager.activatePackage (<embedded>:11:385274)
    at /packages/build-cmd/lib/provider.js:9:195
    at Array.map (<anonymous>:null:null)
    at Object.handleComplete (/packages/build-cmd/lib/provider.js:9:150)
    at /packages/build-cmd/lib/provider.js:11:1018)

```

### Commands

```
     -7:08.5.0 core:confirm (input.hidden-input)
  6x -7:07.0 core:backspace (input.hidden-input)
     -6:51 command-palette:toggle (input.hidden-input)
     -6:49.1.0 editor:consolidate-selections (input.hidden-input)
     -6:49.1.0 core:cancel (input.hidden-input)
     -6:48.4.0 editor:consolidate-selections (input.hidden-input)
     -6:48.4.0 core:cancel (input.hidden-input)
     -6:19.1.0 editor:consolidate-selections (input.hidden-input)
     -6:19.1.0 core:cancel (input.hidden-input)
     -4:13.1.0 platformio-ide-terminal:new (div.platformio-ide-terminal.status-bar)
     -3:37.6.0 platformio-ide-terminal:toggle (textarea.)
     -2:30.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.17.0 
build-cmd 0.10.0 
buildium 0.75.5 
busy-signal 2.0.1 
kite 0.206.0 
platformio-ide-terminal 2.10.1 
```

**Comment by idleberg** [comment]
Do you have a disabled `status-bar` package?
